language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  
install:
  - 'git submodule update'
  - 'composer install'
  - 'composer update'
  
script: 'phpunit --bootstrap "./bootstrap/autoload.php" tests'  
