<?php

$title = new Dreamcoil\Codebowl\Title;

$title->set('Dreamcoil');

$title->append('Welcome');

?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo $title->get() ?></title>
	<style>
	@import url(http://fonts.googleapis.com/css?family=Lato:300);
	@import url(http://fonts.googleapis.com/css?family=Bilbo+Swash+Caps);
	body{
		font-family: 'Lato', sans-serif;
		color: #ecf0f1;
		text-align: center;
		background: #27ae60;
		font-size: 50px;
	}
	.dreamcoil{
		font-family: 'Bilbo Swash Caps', cursive;
		font-size: 125%;
		font-weight: 600;
	}
	</style>
</head>
<body>
	<h1>Come closer ...</h1>
	<p>Yeah that's right, 'cause I gonna tell you a secret called "<span class="dreamcoil">Dreamcoil</span>".<br>
	A simple PhP Framework for all the smooth people on the blue planet.</p>
	Enjoy using <span class="dreamcoil">Dreamcoil</span> on your projects
</body>
</html>
